package com.example.obdvoiceassist.localization

import com.example.obdvoiceassist.models.AppLanguage

object AppStrings {

    fun get(language: AppLanguage): Strings {
        return when (language) {
            AppLanguage.ENGLISH -> english
            AppLanguage.GERMAN -> german
        }
    }

    data class Strings(
        val appName: String,
        val appSubtitle: String,
        val startSetup: String,
        val languageEnglish: String,
        val languageGerman: String,
        val languageLabel: String,
        val notConnected: String,


        val bluetoothSetup: String,
        val bluetoothStatusNotConnected: String,
        val bluetoothPermissionDenied: String,
        val bluetoothPermissionMissing: String,
        val bluetoothNotSupported: String,
        val bluetoothTurnedOff: String,
        val noPairedDevices: String,
        val foundPairedDevices: String,
        val pairedDevices: String,
        val refreshPairedDevices: String,
        val connectToDevice: String,
        val connectingTo: String,
        val connectedTo: String,
        val connectionFailed: String,
        val connectionSuccessful: String,
        val testAtzCommand: String,
        val readAllData: String,
        val goToDashboard: String,
        val obdResponse: String,
        val sendingAtz: String,
        val noResponseReceived: String,
        val readingObdData: String,

        val dashboard: String,
        val liveDataOn: String,
        val liveDataOff: String,
        val liveDataRunning: String,
        val liveDataStarted: String,
        val liveDataStopped: String,
        val liveDataAlreadyRunning: String,
        val liveReadingError: String,
        val liveReadingStoppedDueToError: String,
        val startLive: String,
        val stopLive: String,
        val bluetoothSetupButton: String,
        val valuesUpdateEverySecond: String,
        val vehicleParameters: String,

        val currentSpeed: String,
        val speed: String,
        val rpm: String,
        val coolant: String,
        val throttle: String,
        val engineLoad: String,
        val fuelLevel: String,
        val manifold: String,
        val intakeTemp: String,
        val maf: String,
        val ignition: String,

        val systemStatus: String,
        val drivingAlert: String,
        val criticalAlert: String
    )

    private val english = Strings(
        appName = "OBD Voice Assist",
        appSubtitle = "Live vehicle data with smart voice alerts",
        startSetup = "Start Setup",
        languageEnglish = "English",
        languageGerman = "Deutsch",
        languageLabel = "Language",
        notConnected = "Not Connected",

        bluetoothSetup = "Bluetooth Setup",
        bluetoothStatusNotConnected = "Not connected",
        bluetoothPermissionDenied = "Bluetooth permission denied",
        bluetoothPermissionMissing = "Bluetooth permission missing",
        bluetoothNotSupported = "Bluetooth is not supported on this device",
        bluetoothTurnedOff = "Bluetooth is turned off",
        noPairedDevices = "No paired Bluetooth devices found",
        foundPairedDevices = "Found paired device(s)",
        pairedDevices = "Paired Devices",
        refreshPairedDevices = "Refresh Paired Devices",
        connectToDevice = "Connect",
        connectingTo = "Connecting to",
        connectedTo = "Connected to",
        connectionFailed = "Connection failed",
        connectionSuccessful = "Connection successful. Adapter initialized.",
        testAtzCommand = "Test ATZ Command",
        readAllData = "Read All Data",
        goToDashboard = "Go to Dashboard",
        obdResponse = "OBD Response",
        sendingAtz = "Sending ATZ...",
        noResponseReceived = "No response received",
        readingObdData = "Reading OBD data...",

        dashboard = "OBD Dashboard",
        liveDataOn = "Live Data: ON",
        liveDataOff = "Live Data: OFF",
        liveDataRunning = "Live data running...",
        liveDataStarted = "Live data reading started",
        liveDataStopped = "Live data reading stopped",
        liveDataAlreadyRunning = "Live reading is already running",
        liveReadingError = "Live reading error",
        liveReadingStoppedDueToError = "Live reading stopped due to error",
        startLive = "Start Live",
        stopLive = "Stop Live",
        bluetoothSetupButton = "Bluetooth Setup",
        valuesUpdateEverySecond = "Values update automatically when live mode is active.",
        vehicleParameters = "Vehicle Parameters",

        currentSpeed = "CURRENT SPEED",
        speed = "Speed",
        rpm = "RPM",
        coolant = "Coolant",
        throttle = "Throttle",
        engineLoad = "Engine Load",
        fuelLevel = "Fuel Level",
        manifold = "Manifold",
        intakeTemp = "Intake Temp",
        maf = "MAF",
        ignition = "Ignition",

        systemStatus = "System Status",
        drivingAlert = "Driving Alert",
        criticalAlert = "Critical Alert"
    )

    private val german = Strings(
        appName = "OBD Sprachassistent",
        appSubtitle = "Live-Fahrzeugdaten mit intelligenten Sprachwarnungen",
        startSetup = "Einrichtung starten",
        languageEnglish = "English",
        languageGerman = "Deutsch",
        languageLabel = "Sprache",
        notConnected = "Nicht Verbunden",

        bluetoothSetup = "Bluetooth-Einrichtung",
        bluetoothStatusNotConnected = "Nicht verbunden",
        bluetoothPermissionDenied = "Bluetooth-Berechtigung verweigert",
        bluetoothPermissionMissing = "Bluetooth-Berechtigung fehlt",
        bluetoothNotSupported = "Bluetooth wird auf diesem Gerät nicht unterstützt",
        bluetoothTurnedOff = "Bluetooth ist ausgeschaltet",
        noPairedDevices = "Keine gekoppelten Bluetooth-Geräte gefunden",
        foundPairedDevices = "Gekoppelte Geräte gefunden",
        pairedDevices = "Gekoppelte Geräte",
        refreshPairedDevices = "Gekoppelte Geräte aktualisieren",
        connectToDevice = "Verbinden",
        connectingTo = "Verbinde mit",
        connectedTo = "Verbunden mit",
        connectionFailed = "Verbindung fehlgeschlagen",
        connectionSuccessful = "Verbindung erfolgreich. Adapter initialisiert.",
        testAtzCommand = "ATZ-Befehl testen",
        readAllData = "Alle Daten lesen",
        goToDashboard = "Zum Dashboard",
        obdResponse = "OBD-Antwort",
        sendingAtz = "Sende ATZ...",
        noResponseReceived = "Keine Antwort erhalten",
        readingObdData = "OBD-Daten werden gelesen...",

        dashboard = "OBD-Dashboard",
        liveDataOn = "Live-Daten: EIN",
        liveDataOff = "Live-Daten: AUS",
        liveDataRunning = "Live-Daten laufen...",
        liveDataStarted = "Live-Datenübertragung gestartet",
        liveDataStopped = "Live-Datenübertragung gestoppt",
        liveDataAlreadyRunning = "Live-Daten laufen bereits",
        liveReadingError = "Fehler beim Lesen der Live-Daten",
        liveReadingStoppedDueToError = "Live-Datenübertragung wegen eines Fehlers gestoppt",
        startLive = "Live starten",
        stopLive = "Live stoppen",
        bluetoothSetupButton = "Bluetooth-Einrichtung",
        valuesUpdateEverySecond = "Werte werden im Live-Modus automatisch aktualisiert.",
        vehicleParameters = "Fahrzeugparameter",

        currentSpeed = "AKTUELLE GESCHWINDIGKEIT",
        speed = "Geschwindigkeit",
        rpm = "Drehzahl",
        coolant = "Kühlmittel",
        throttle = "Drosselklappe",
        engineLoad = "Motorlast",
        fuelLevel = "Kraftstoffstand",
        manifold = "Ansaugdruck",
        intakeTemp = "Ansauglufttemp.",
        maf = "Luftmasse",
        ignition = "Zündung",

        systemStatus = "Systemstatus",
        drivingAlert = "Fahrwarnung",
        criticalAlert = "Kritische Warnung"
    )
}